### PR TITLE
Vite upgrade

### PR DESCRIPTION
**Pull request by PascalGolla**
Replaces deprecated create-react-app (react-scripts) with [vite](https://vitejs.dev/)

Todos:

- [x] Check github action
- [x] Check standalone application

### CODE REVIEW

**Comment by FabianRolfMatthiasNoll** [comment]
The Workflow now works again. But the standalone application doesnt work anymore. Still need to fix that. But everything else i really like the small changes here and there and also the overall cleanup. npm install and build run now way faster.

**Comment by PascalGolla** [comment]
My first guess would be in the [main.py](https://github.com/FabianRolfMatthiasNoll/MyMangaDB/blob/vite-upgrade/main.py) at line 20.

Vite generates a ./dist/ directory instead of the ./build/ one.

**Comment by PascalGolla** [comment]
Also for the pyinstaller build command, the directory change must also be considered

**Comment by FabianRolfMatthiasNoll** [comment]
Yeah you are completly right. I changed the directory everywhere but forgot it in the main.py

**Comment by FabianRolfMatthiasNoll** [comment]
Successfully fixed

**Review by FabianRolfMatthiasNoll — APPROVED** [review]

**Pull request merged**
